### PR TITLE
abstract for xarray paper

### PR DESCRIPTION
**Pull request by rabernat**
cc @shoyer @jhamman

### CODE REVIEW

**Comment by jhamman** [comment]
LGTM.  Thanks @rabernat.

**Comment by shoyer** [comment]
Indeed, thanks Ryan! This looks great.

**Comment by aterrel** [comment]
Thanks!

**Comment by rabernat** [comment]
@aterrel: I know we have a Nov. 15 deadline coming up. Give the travel schedules of our authors over the next week, meeting this would probably require some long, late nights. Is there some wiggle room in the deadline, say until after the Thanksgiving holiday? If not, we could pull it off, but I thought I would check with you first.

**Comment by aterrel** [comment]
yeah totally.

I don't expect anyone to keep that deadline. Perhaps I should send an email
or something.

**Comment by rabernat** [comment]
> I don't expect anyone to keep that deadline. Perhaps I should send an email
> or something.

This is very good to hear. The README on the main page sets a pretty tight schedule, so your clarification is appreciated.

We will aim to have a mostly complete draft submitted by Dec. 1.

**Comment by rabernat** [comment]
@jhamman, @shoyer: I am finally getting on this.

I just wrote an introduction and put in a proposed outline. I realized I am confused about the scope of this chapter: I don't know how much basic vs. advanced material they are looking for. My solution has been to divide into three sections: basic usage, reading / writing data, advanced example.

For the basic usage section, a lot of what would go in there could potentially be copied more-or-less verbatim from the docs. Is there any copyright / license issue which would prevent us from doing that?

As for the other sections, I plan to start working on a tutorial example now. But I thought I would push my commits and get your feedback on the outline.

**Comment by shoyer** [comment]
I wrote most of the basic usage examples in the docs, but the copyright is owned by my former employer. That said, it's all Apache licensed. I don't know if that's good enough.

**Pull request merged**
