### PR TITLE
PyMC3 Chapter

### PR DESCRIPTION
**Pull request by mmargenot**
This is the in-progress PyMC3 Chapter. Graphics need to be updated and citations fleshed out.

### CODE REVIEW

**Comment by twiecki** [comment]
@aterrel What's the status of the PyData cookbook? I reviewed and edited the chapter and think it looks great. Let me know what you think and potential next steps.

CC @fonnesbeck.

**Comment by aterrel** [comment]
Thanks for the submission. I'm talking to Pearson today to get their timeline together.

**Comment by twiecki** [comment]
@aterrel what's the status of this?

**Comment by aterrel** [comment]
@twiecki Did you not get my email? Just want to make sure we have you on the mailing list.

We have a few chapters in and want all others to try and submit by March 31.

**Comment by twiecki** [comment]
@aterrel Haven't gotten anything in a while.

**Pull request merged**
