### PR TITLE
[WIP] XGBoost Chapter

### PR DESCRIPTION
**Pull request by terrytangyuan**
Here's the abstract for XGBoost chapter. Any feedback would be appreciated. 

cc: @phunterlau

### CODE REVIEW

**Comment by aterrel** [comment]
This looks great. Thanks!

**Comment by terrytangyuan** [comment]
@phunterlau I accidentally merged it to master branch of my fork but let's just keep everything in this one PR then (@aterrel if you don't mind). 

@aterrel What's updated deadline given the holiday schedule?

**Comment by aterrel** [comment]
That works fine.

I'll get back to you about the deadline.

**Comment by terrytangyuan** [comment]
Any updates? @aterrel

**Comment by aterrel** [comment]
@terrytangyuan Right now I would like to have the book finished in the next 3 months. I'm asking everyone to give me their deadlines to help. Let me know when ya'll can be finished.

**Comment by terrytangyuan** [comment]
Thanks. We will aim for ~ 2 months.

**Comment by terrytangyuan** [comment]
@aterrel Any updates on the timeline? Are we all still aiming for this book?

**Comment by aterrel** [comment]
Yes the publisher is going to be sending out some details this week.

**Pull request merged**
