### PR TITLE
Add abstract for SymPy

### PR DESCRIPTION
**Pull request by asmeurer**
Let me know if this is what you're looking for. I'm unclear who the exact audience of this book is, and how much of the chapter should focus on introducing SymPy, on demonstrating SymPy's specific workflows for scientists (specifically, code generation), or on interoperating SymPy through other librarys (which is related to code generation).  I also am not clear on how long the chapter should be.

### CODE REVIEW

**Comment by aterrel** [comment]
yup that looks great!

**Comment by asmeurer** [comment]
Is this alive again?

**Comment by aterrel** [comment]
Yes, I'll be updating the schedule this week.

**Comment by aterrel** [comment]
@asmeurer  Right now I would like to have the book finished in the next 3 months. I'm asking everyone to give me their deadlines to help. Let me know when ya'll can be finished.

**Comment by asmeurer** [comment]
I can make that deadline. Please let me know when the hard deadline is.

Also, I never received answers to the questions I asked in the OP.

**Comment by aterrel** [comment]
10 - 20 page chapters

Interested in the integration in scientific workflows as you mentioned in the abstract, not an intro tutorial but you will probably need some introductory material

The audience is scientist (data and others) in academic and professional contexts wanting to get a bit deeper dive into the PyData tools.

**Pull request merged**
