### PR TITLE
Scikit-Image chapter

### PR DESCRIPTION
**Pull request by JDWarner**
Supersedes #6.

There is at least one more example from a coauthor which is not yet submitted but will be incorporated, and our fearless leader will find time to properly introduce the chapter.  However, this is otherwise in readable shape, before the deadline by at least 10 minutes ;)

Where the code provided in the chapter does not fully produce the published figures (usually for Matplotlib formatting brevity), I have included reproduction notebooks which do. 

TODO: 
*  Section about distributed/parallel processing with `dask` (@stefanv?)
*  Address reviewer/coauthor comments

### CODE REVIEW

**Comment by JDWarner** [comment]
This is now in good shape from my standpoint.  @stefanv would you like to add a section on `dask`/parallel work?  Any other examples you'd like to include?

Ping coauthors @emmanuelle, @alexandrejaguar, @stefanv for review/edits.

**Comment by alexdesiqueira** [comment]
@JDWarner I read this version and looks very good to me. The denoising part was drastically improved; thanks for that. Maybe on [2] we could put a link to instructions on installing the `dev` version. However, I think the 0.13 will be released before the book is out.

**Comment by stefanv** [comment]
Sorry for the silence!  I will read and comment & add an intro section tomorrow morning California time.  Thanks a lot for all your hard work so far!

**Comment by stefanv** [comment]
Hey, Josh, can you give me push access to your branch, please?  In the mean time, I've made a PR against your branch.

**Comment by JDWarner** [comment]
@stefanv merged in, and you should now have push access!

**Pull request merged**
