### PR TITLE
WIP: add abstract for SciPy

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
Ping @ev-br @WarrenWeckesser

Warren, do you want to list an institution?

Abstract will be completed soon, just wanted to get this PR now that we have an author list.

**Comment by rgommers** [comment]
Ping @ev-br @WarrenWeckesser

Warren, do you want to list an institution?

Abstract will be completed soon, just wanted to get this PR now that we have an author list.

**Comment by rgommers** [comment]
Ping @ev-br @WarrenWeckesser

Warren, do you want to list an institution?

Abstract will be completed soon, just wanted to get this PR now that we have an author list.

**Comment by WarrenWeckesser** [comment]
No institution.  I guess you could say I'm in what the startup folks call "stealth mode".  Yeah, that's it, _stealth mode_.

**Comment by justbennet** [comment]
Ralf, per request, here is a comment identifying myself.

Hi, Warren.  Thanks for the help a while back.

**Comment by WarrenWeckesser** [comment]
Hi Bennet!

**Comment by aterrel** [comment]
Hi all! This is great. Thanks so much for starting the submission.

**Pull request merged**
